### ISSUE TITLE
Redo Risk analysis

### ISSUE THREAD

**Issue by SSM121** [SSM121/2ndPlaceBestPlace#20]
Graders Notes:
For an example of what type of risk analysis we're looking for take a look at pg. 48 of the textbook.

What we are looking for is taking a couple key functional requirements and looking at: Likelihood, Severity, Consequences, and Work-arounds.

**Comment by Soclemens** [comment]
I am assigning this to Nathan because he is the one who claimed this deliverable on the last sprint. If anyone has time to rework this before Nathan gets a chance please claim this item

**Comment by icemanjr** [comment]
Updated, we now have likelihood, severity, consequences, and work-arounds for all main Functional Requirements.
